name: 'Barum GitHub Action - Hello World'

description: 'A custom GitHub action that greets a user.'

inputs:
  who-to-greet:
    description: 'The name to greet'
    required: true
    default: World

outputs:
  time: #id of the output
    description: The time we greet you

runs:
  using: 'node20'
  main: 'dist/index.js'
